# Generated by Django 4.0.2 on 2022-02-21 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_time', models.CharField(choices=[('1230', '12:30'), ('1430', '14:30'), ('1630', '16:30'), ('1830', '18:30')], default='1230', max_length=4)),
                ('fdra', models.CharField(choices=[('COTI', 'Coastal Timber'), ('SISH', 'Sierra de Salinas Shrub'), ('SAGR', 'Salinas Valley Grass'), ('GBSH', 'Gabilan Shrub'), ('DIGR', 'Diablo Grass')], max_length=4)),
                ('dl_userSet', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('V', 'Very High')], max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
